language: go

go:
- 1.14.x

services:
  - postgresql

script:
- go get github.com/golangci/golangci-lint/cmd/golangci-lint
- export PATH=$PATH:$(go env GOPATH)/bin && golangci-lint run
- make migrate
- make test
