language: go

go:
- 1.14.x

services:
  - postgresql

script:
- go get github.com/golangci/golangci-lint/cmd/golangci-lint
- make lint
- make migrate
- go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
