language: go

go:
- 1.14.x

services:
- docker

postgres:
  adapter: postgresql
  database: postgres
  username: postgres

before_script:
  - "psql -c 'create database postgres;' -U postgres"

script:
- make migrate
- make test
